### ISSUE TITLE
 Request for Training Code

### ISSUE THREAD

**Issue by Hanxingzhuang111** [wwsource/SplatFlow#1]
Hi,
Thank you for your amazing work on SplatFlow. I noticed that the repository currently only contains the inference code. Could you please provide the training code or any guidance on how to train the model from scratch?
This would be very helpful for further research and applications.
Thanks in advance!

**Comment by wwsource** [comment]
Thank you for noticing our work and for your suggestions!🥰
We are commencing the organization of the training code. 
The release of the training code is scheduled for June. If circumstances allow, it may be released sooner. Stay tuned!

**Comment by wwsource** [comment]
@Hanxingzhuang111 
The training and testing code is released! I hope it can be helpful for your work. If you have any queries, please don't hesitate to contact me~

**Comment by wwsource** [comment]
@Hanxingzhuang111 
If there are no other questions, I will close this issue.
Best wishes to you.
