### ISSUE TITLE
Trained weights can not accessible

### ISSUE THREAD

**Issue by Ahmet-Kaplan** [wwsource/SplatFlow#2]
Unfortunately [Weight Downloads](https://pan.baidu.com/s/1JDPCexLqlj-ULLt1TPsGxA&pwd=wang) link was expired.

**Comment by wwsource** [comment]
If you cannot download the weight from Baidu Netdisk, you can try through the Huggingface link [https://huggingface.co/wwcreator/SplatFlow](https://huggingface.co/wwcreator/SplatFlow).
